### ISSUE TITLE
Crashes due to unexpected type 'float'

### ISSUE THREAD

**Issue by CalmeaLin** [Calmea/labelImg#1]
**Describe the bug**
Attempting to zoom via mouse wheel or to draw a bounding box results in an immediate crash. Here's the output when I try to draw a bounding box:

```
Traceback (most recent call last):
  File "/home/stan/.conda/envs/pytorch_cuda3090/lib/python3.10/site-packages/labelImg/labelImg.py", line 1014, in zoom_request
    self.add_zoom(scale * units)
  File "/home/stan/.conda/envs/pytorch_cuda3090/lib/python3.10/site-packages/labelImg/labelImg.py", line 974, in add_zoom
    self.set_zoom(self.zoom_widget.value() + increment)
  File "/home/stan/.conda/envs/pytorch_cuda3090/lib/python3.10/site-packages/labelImg/labelImg.py", line 971, in set_zoom
    self.zoom_widget.setValue(value)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
zsh: IOT instruction (core dumped)  labelImg
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
```
$ uname -rvsmio
# Linux 5.19.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 29 Aug 2022 15:51:05 +0000 x86_64 unknown GNU/Linux

$ conda list | grep -E '(qt)|(labelimg)'
# labelimg                  1.8.6           py310hff52083_1    conda-forge
# pyqt                      5.15.7          py310h29803b5_0    conda-forge
# pyqt5-sip                 12.11.0         py310hd8f1fbe_0    conda-forge
# qt-main                   5.15.4               ha5833f6_2    conda-forge
```

**Comment by CalmeaLin** [comment]
Solution:
Error in Qt5.
float to int conversion
Changed:
x:\xxxxx\python-310\Lib\site-packages\libs\canvas.py
526 line:
`p.drawRect(int(left_top.x()), int(left_top.y()), int(rect_width), int(rect_height))`
530 line:
`p.drawLine( int(self.prev_point.x()), 0, int(self.prev_point.x()), int(self.pixmap.height()))`
531 line:
`p.drawLine( 0, int(self.prev_point.y()), int(self.pixmap.width()), int(self.prev_point.y()))`
Changed:
**x:\xxxxx\python-310\Lib\site-packages\labelImg\labelImg.py**
965 line:
`bar.setValue(int(bar.value() + bar.singleStep() * units))`
971 line:
`self.zoom_widget.setValue(int(value))`
1025 line:
```
h_bar.setValue(int(new_h_bar_value))
v_bar.setValue(int(new_v_bar_value))
```


``
**lib\site-packages\libs\shape.py**
131 line:
`painter.drawText(int(min_x), int(min_y), self.label)`
